import Nav from '@/components/Navigation/Nav'
import './globals.css'
import type { Metadata } from 'next'
import { Playfair_Display, Great_Vibes } from 'next/font/google'

const greatVibes = Great_Vibes({
	subsets: ['latin-ext'],
	weight: ['400'],
	variable: '--font-great-vibes',
})
const playFairDisplay = Playfair_Display({
	subsets: ['latin-ext'],
	weight: ['400', '700'],
	variable: '--font-playfair-display',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html
			lang='en'
			className={`${greatVibes.variable} ${playFairDisplay.variable}`}>
			<body className='text-darkText font-playFair'>
				<Nav />
				{children}
			</body>
		</html>
	)
}
